const courses = [
  {
    id: 1,
    title: 'E-commerce Course',
    duration: '14 Weeks | 5 classes per Week',
    Mode: 'On-Campus / Online',
    learn: [
      'Winning Product Hunting (Tools & Technique)',
      'Smart Products Sourcing (Wholesale & Local Vendors)',
      'Product Photography & Graphic Design',
      'Facebook & Whatsapp Marketing',
      'Pricing Strategy & Profit Calculation',
      'Order Dealing & Delivery Process',
      'Customer Handling & After-Sales Support',
    ],
    Join: [
      'Students',
      'Beginners in E-Commerce',
      'Home-Based Entrepreneurs',
      'Small Business Owners',
    ],
    Outcome: [
      'Own E-commerce Business Setup',
      'Local Selling System',
      'Complete Digital Marketing Skill',
      'Certificate of Completion',
    ],
    Fee: '25000',
  },
  {
    id: 2,
    title: 'Web Development',
    duration: '12 Weeks | 5 classes per Week',
    Mode: 'On-Campus / Online',
    learn: [
      'HTML, CSS, JavaScript Basics',
      'Responsive Web Design',
      'React.js & Component Structure',
      'API Integration',
      'Git & GitHub Basics',
      'Deployment Techniques',
      'Project-Based Learning',
    ],
    Join: [
      'Students',
      'Beginners in Coding',
      'Home-Based Coders',
      'Aspiring Developers',
    ],
    Outcome: [
      'Build Web Applications',
      'Understand Full Frontend Flow',
      'Portfolio for Freelancing',
      'Certificate of Completion',
    ],
    Fee: '15000',
  },
  {
    id: 3,
    title: 'App Development',
    duration: '10 Weeks | 3 classes per Week',
    Mode: 'Online',
    learn: [
      'React Native Basics',
      'UI/UX Principles',
      'API Integration',
      'Publishing Apps on Play Store & App Store',
    ],
    Join: ['Students', 'Beginners in Coding', 'App Enthusiasts'],
    Outcome: [
      'Build Mobile Applications',
      'Publish to App Stores',
      'Portfolio for Freelancing',
      'Certificate of Completion',
    ],
    Fee: '18000',
  },
];

export default courses;
