const courses = [
  {
    id: 1,
    title: 'E-commerce Course',
    duration: '14 Weeks | 5 classes per Week',
    Mode: 'On-Campus / Online',
    learn: [
      'Winning Product Hunting (Tools & Technique)',
      'Smart Products Sourcing (Wholesale & Local Vendors)',
      'Product Photography & Graphic Design',
      'Facebook & Whatsapp Marketing',
      'Pricing Strategy & Profit Calculation',
      'Order Dealing & Delivery Process',
      'Customer Handling & After-Sales Support',
    ],
    Join: [
      'Students',
      'Beginners in E-Commerce',
      'Home-Based Entrepreneurs',
      'Small Business Owners',
    ],
    Outcome: [
      'Own E-commerce Business Setup',
      'Local Selling System',
      'Complete Digital Marketing Skill',
      'Certificate of Completion',
    ],
    Fee: '25000',
  },
  {
    id: 2,
    title: 'Web Development',
    duration: '12 Weeks | 5 classes per Week',
    Mode: 'On-Campus / Online',
    learn: [
      'HTML, CSS, JavaScript Basics',
      'Responsive Web Design',
      'React.js & Component Structure',
      'API Integration',
      'Git & GitHub Basics',
      'Deployment Techniques',
      'Project-Based Learning',
    ],
    Join: [
      'Students',
      'Beginners in Coding',
      'Home-Based Coders',
      'Aspiring Developers',
    ],
    Outcome: [
      'Build Web Applications',
      'Understand Full Frontend Flow',
      'Portfolio for Freelancing',
      'Certificate of Completion',
    ],
    Fee: '15000',
  },
  {
    id: 3,
    title: 'App Development',
    duration: '10 Weeks | 3 classes per Week',
    Mode: 'Online',
    learn: [
      'React Native Basics',
      'UI/UX Principles',
      'API Integration',
      'Publishing Apps on Play Store & App Store',
    ],
    Join: ['Students', 'Beginners in Coding', 'App Enthusiasts'],
    Outcome: [
      'Build Mobile Applications',
      'Publish to App Stores',
      'Portfolio for Freelancing',
      'Certificate of Completion',
    ],
    Fee: '18000',
  },
  {
    id: 4,
    title: 'Digital Marketing Mastery',
    duration: '8 Weeks | 4 classes per Week',
    Mode: 'Online / On-Campus',
    learn: [
      'Social Media Marketing (Facebook, Instagram, TikTok)',
      'Search Engine Optimization (SEO)',
      'Content Creation & Strategy',
      'Email Marketing & Automation',
      'Google Ads & Paid Campaigns',
    ],
    Join: [
      'Students',
      'Small Business Owners',
      'Freelancers',
      'Marketing Enthusiasts',
    ],
    Outcome: [
      'Complete Digital Marketing Skill',
      'Run Campaigns for Businesses',
      'Increase Online Sales & Engagement',
      'Certificate of Completion',
    ],
    Fee: '12000',
  },
  {
    id: 5,
    title: 'Graphic Design & Branding',
    duration: '6 Weeks | 3 classes per Week',
    Mode: 'Online / On-Campus',
    learn: [
      'Adobe Photoshop & Illustrator',
      'Logo Design & Brand Identity',
      'Social Media Graphics',
      'UI/UX Basics for Designers',
      'Portfolio Creation',
    ],
    Join: [
      'Students',
      'Freelancers',
      'Aspiring Designers',
      'Entrepreneurs',
    ],
    Outcome: [
      'Design Professional Graphics',
      'Build Brand Identity for Businesses',
      'Portfolio for Freelancing',
      'Certificate of Completion',
    ],
    Fee: '10000',
  },
  {
    id: 6,
    title: 'Python Programming & Data Science',
    duration: '10 Weeks | 4 classes per Week',
    Mode: 'Online / On-Campus',
    learn: [
      'Python Basics & Data Structures',
      'Pandas & NumPy for Data Analysis',
      'Matplotlib & Seaborn for Visualization',
      'Machine Learning Fundamentals',
      'Projects & Portfolio Building',
    ],
    Join: [
      'Students',
      'Beginners in Coding',
      'Data Enthusiasts',
      'Career Changers',
    ],
    Outcome: [
      'Build Data Science Projects',
      'Analyze Real-World Datasets',
      'Understand ML Basics',
      'Certificate of Completion',
    ],
    Fee: '20000',
  },
];

export default courses;
